### ISSUE TITLE
fill with numeric value is needed for tile twowaycount to work correctly

### ISSUE THREAD

**Issue by EvaMaeRey** [EvaMaeRey/ggpivot#1]
################
#  This works ....
############

compute_group_twowaycountfill <- function(data, scales){

  data %>%
    # add an additional column called label
    # the geom we inherit from requires the label aesthetic
    dplyr::count(x, y) %>%
    dplyr::rename(fill = n)

}

StatTwowaycountfill <- ggplot2::ggproto(`_class` = "Twowaycount",
                                  `_inherit` = ggplot2::Stat,
                                  required_aes = c("x", "y", "fill"),   #  This 
                                  compute_group = compute_group_twowaycountfill)

geom_tile_twowaycount <- function(mapping = NULL, data = NULL,
                                  position = "identity", na.rm = FALSE,
                                  show.legend = NA,
                                  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatTwowaycountfill, # proto object from Step 2
    geom = ggplot2::GeomTile, # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

library(ggplot2)
ggplot(data = mtcars) +
aes(x = cyl, y = gear) +
geom_tile_twowaycount() +
aes(fill = 1) +  # required for good result but it isn't used.  It's because it is a numeric input I think
geom_text_twowaycount()

#######
############

compute_group_twowaycountfill <- function(data, scales){

  data %>%
    # add an additional column called label
    # the geom we inherit from requires the label aesthetic
    dplyr::count(x, y) %>%
    dplyr::rename(fill = n)

}

StatTwowaycountfill <- ggplot2::ggproto(`_class` = "Twowaycount",
                                  `_inherit` = ggplot2::Stat,
                                  required_aes = c("x", "y"),     #this s
                                  compute_group = compute_group_twowaycountfill)

geom_tile_twowaycount <- function(mapping = NULL, data = NULL,
                                  position = "identity", na.rm = FALSE,
                                  show.legend = NA,
                                  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatTwowaycountfill, # proto object from Step 2
    geom = ggplot2::GeomTile, # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

library(ggplot2)
ggplot(data = mtcars) +
aes(x = cyl, y = gear) +
geom_tile_twowaycount() +
geom_text_twowaycount()

**Comment by yjunechoe** [comment]
You can move the mapping from `n` to `fill` outside of `compute_group()` into `default_aes`!

``` r
library(ggtrace)
library(ggplot2)
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.1.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

compute_group_twowaycountfill <- function(data, scales){
  
  data %>%
    dplyr::count(x, y) # %>%
    # dplyr::rename(fill = n) #< remove this line
  
}

StatTwowaycountfill <- ggplot2::ggproto(`_class` = "Twowaycount",
                                         `_inherit` = ggplot2::Stat,
                                         required_aes = c("x", "y"),
                                         default_aes = aes(fill = after_stat(n)), #< add this line!
                                         compute_group = compute_group_twowaycountfill)

geom_tile_twowaycount <- function(mapping = NULL, data = NULL,
                                  position = "identity", na.rm = FALSE,
                                  show.legend = NA,
                                  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatTwowaycountfill,
    geom = ggplot2::GeomTile,
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

ggplot(data = mtcars) +
  aes(x = cyl, y = gear) +
  geom_tile_twowaycount()
```

![](https://i.imgur.com/dRHLE6G.png)

<sup>Created on 2022-03-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
